### ISSUE TITLE
Cookies.md not displaying under Desserts in GitBook

### ISSUE THREAD

**Issue by katiemillsau** [sarasrking/the_food_book_sandbox#3]
Cookies.md is not displaying under the Desserts heading in the GitBook. Do we need to synchronise the two somehow?

**Comment by sarasrking** [comment]
There is a problem I created with setting up another branch and the GitHub integration. Will have to work that out!

**Comment by sarasrking** [comment]
It's still not displaying - and there are some other changes here that aren't reflected in the GitBook. I wonder if there is supposed to be a 'merge' stage?

**Comment by katiemillsau** [comment]
Yes, it looks like this might be due to the two branches (main and master)?

**Comment by katiemillsau** [comment]
There are quite a few pages that aren't showing - vegan delights is another one.

**Comment by sarasrking** [comment]
OK so I switched 'main' from the default to 'master' so it matches the GitBook as it is. And then I deleted the 'main' branch. So that might have been where those changes were made.

**Comment by sarasrking** [comment]
I wonder if I could have merged the two branches? Hmm

**Comment by katiemillsau** [comment]
I think I just solved this! When you add a new file in GitHub, you then need to add a link to the page in SUMMARY.md for it to appear in the Table of Contents. I was missing that step! Apologies if this was already common knowledge.

**Comment by sarasrking** [comment]
Definitely not common knowledge. I think this is a good tip to add to our list in the cook book. I didn't know that.
